/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
    export interface GlobalComponents {
        HelloWorld: typeof import('./../components/HelloWorld.vue')['default']
        NButton: typeof import('naive-ui')['NButton']
        NH2: typeof import('naive-ui')['NH2']
        NP: typeof import('naive-ui')['NP']
        NSpace: typeof import('naive-ui')['NSpace']
        NText: typeof import('naive-ui')['NText']
        RouterLink: typeof import('vue-router')['RouterLink']
        RouterView: typeof import('vue-router')['RouterView']
        SvgIcon: typeof import('./../components/SvgIcon.vue')['default']
    }
}
