/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
    export interface GlobalComponents {
        AppLoading: typeof import('./../components/common/AppLoading.vue')['default']
        NButton: typeof import('naive-ui')['NButton']
        NConfigProvider: typeof import('naive-ui')['NConfigProvider']
        NDialogProvider: typeof import('naive-ui')['NDialogProvider']
        NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
        NH2: typeof import('naive-ui')['NH2']
        NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
        NMessageProvider: typeof import('naive-ui')['NMessageProvider']
        NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
        NP: typeof import('naive-ui')['NP']
        NText: typeof import('naive-ui')['NText']
        RouterLink: typeof import('vue-router')['RouterLink']
        RouterView: typeof import('vue-router')['RouterView']
        SvgIcon: typeof import('./../components/SvgIcon.vue')['default']
    }
}
